title: "SatoshiDollarParity"
description: "Bitcoin, blockchain, and financial inclusion insights"
theme: jekyll-theme-minimal

# Basic customizations
baseurl: "" # leave this empty unless you’re hosting under a subpath
url: "https://www.satoshidollarparity.com" # or your custom domain if configured

# Social links (you can add more links if needed)
social_links:
  - name: GitHub
    url: https://github.com/wallclockbuilder
    url: https://github.com/SatoshiDollarParity
  - name: LinkedIn
    url: https://www.linkedin.com
  - name: YouTube
    url: https://www.youtube.com/@SatoshiDollarParity

# Footer settings
footer_text: "SatoshiDollarParity © 2024"
email: madzoe@satoshidollarparity.com

# Analytics (optional)
google_analytics: UA-XXXXXX-X # Replace with your Google Analytics tracking ID

# Optional additional customization
markdown: kramdown
highlighter: rouge # Syntax highlighter for code snippets

# SEO optimization (optional)
seo:
  description: "The best insights on Bitcoin, blockchain, and financial inclusion."
  keywords: "Bitcoin, blockchain, financial inclusion, SatoshiDollarParity"
  author: "SatoshiDollarParity"
